# Explicit sudo:false to run on Travis containers (much faster)
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - jkeiren/ppa
    packages:
      - gcc-4.7
      - g++-4.7
      - clang

language: cpp
compiler:
  - clang
  - gcc

script: ./scripts/travis.sh
