# Explicit sudo:false to run on Travis containers (much faster)
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - jkeiren/ppa
    packages:
      - gcc-4.7
      - g++-4.7
      - clang

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

language: cpp
compiler:
  - clang
  - gcc

script: ./scripts/travis.sh
